---
# flavor
test_flavor: s3.medium.2

# cloud_name:
test_keypair_name: api_monitoring_test
test_security_group_name: test_sg
test_server_fqdn: test_scenario.bastion.host
# test_server_fqdn: bastion.example.com

# those hosts are used in the scenario30 to watch latencies
watch_hosts:
  - host: "https://console.otc.t-systems.com"
    name: "console"
  - host: "https://docs.otc.t-systems.com"
    name: "docs"

# This is used by scenario31 - nslookup
nslookup_public:
  ns_servers: 
    - ns1.open-telekom-cloud.com.
    - ns2.open-telekom-cloud.com.
  records:
    - console.otc.t-systems.com
    - docs.otc.t-systems.com
    - record: iam.eu-de.otc.t-systems.com
      name: iam_de
