---
# cloud_name:
test_keypair_name: api_monitoring_test
test_security_group_name: test_sg
test_server_fqdn: test_scenario.bastion.host
# test_server_fqdn: bastion.example.com

# those hosts are used in the scenario30 to watch latencies
watch_hosts:
  - host: "https://console.otctest.t-systems.com"
    name: "console"
  - host: "https://docs.otctest.t-systems.com"
    name: "docs"
