---

- name: Scenario 1 - obtain token
  hosts: localhost
  ignore_errors: yes
  tasks:
    - name: Check identity endpoint
      script: check_identity_ep.py

    - name: Get token
      script: get_token.py
