---

# Scenario for pinging specific domains measuring latency
- name: Scenario30 - Domain latencies
  hosts: localhost
  tasks:
    - name: Measure latency
      apimon_latency:
        hosts: "{{ watch_hosts }}"
      register: latencies

    - debug:
        var: latencies

    - name: Pause for 10 seconds
      pause:
        seconds: 10

