---

# Scenario for pinging specific domains measuring latency
- name: Scenario30 - Domain latencies
  hosts: localhost
  tasks:
    - name: Measure latency
      ansible.builtin.script: "apimon_latency.py {{ item.host }} {{ item.name }} 5"
      args:
        executable: "/usr/bin/python3"
      loop: "{{ watch_hosts }}"

    - name: Pause for 10 seconds
      pause:
        seconds: 10

