---

- name: Scenario 1 - obtain token
  hosts: localhost
  ignore_errors: yes
  tasks:
    - name: Get token
      script: get_token.py
      tags: 'service=identity'

    - name: Get token from token
      script: get_token_from_token.py
      tags: 'service=identity'
