---

# Scenario to test bascic Image functions
#
- name: Scenario 4 - Image
  hosts: localhost
  vars:
    prefix: scenario4-
  tasks:
    - set_fact:
        prefix: "{{ (prefix + ( lookup('env', 'TASK_EXECUTOR_JOB_ID') | default(99999999 | random | to_uuid | hash('md5'), true) ) ) }}"

    - block:

      - name: List Images
        os_image_info:

      - name: Get single Image
        os_image_info:
          image: Standard_Fedora_30_latest

      - name: Create directory for images
        file:
          name: /tmp/ansible/images
          state: directory
          recurse: true

      - name: Download cirros image
        get_url:
          url: https://download.cirros-cloud.net/0.5.0/cirros-0.5.0-x86_64-disk.img
          dest: /tmp/ansible/images/cirros.img
          validate_certs: false

      - name: Upload cirros image
        os_image:
          name: cirros
          container_format: bare
          disk_format: qcow2
          state: present
          min_disk: 1
          timeout: 1200
          filename: /tmp/ansible/images/cirros.img
        tags:
          - "metric=image_upload"

      always:

        - name: Delete cirros image
          os_image:
            name: cirros
            state: absent
          tags:
            - "metric=image_delete"
