---

# Scenario to test EVS deployment in different AZs
#
- name: Scenario 3a - Storage per AZ
  hosts: localhost
  vars:
    prefix: scenario3a-
  tasks:
    - set_fact:
        prefix: "{{ (prefix + ( lookup('env', 'TASK_EXECUTOR_JOB_ID') | default(99999999 | random | to_uuid | hash('md5'), true) ) ) }}"

    - set_fact:
        test_volume_name: "{{ (prefix + '-test_volume_apimon') }}"

    - block:

      - name: Get network facts
        os_networks_info:
          name: admin_external_net
        register: nets

      - set_fact:
          network_azs: "{{ nets['openstack_networks'][0]['availability_zones'] }}"

      - name: "Create Volume in {{item}}"
        include_role:
          name: volume_create_delete
        vars:
          volume_name: "{{ (item + '.' + test_volume_name) }}"
          availability_zone: "{{ item }}"
          size: 10
          display_name: "{{volume_name}}"
        loop: "{{ network_azs }}"
