---
- name: test
  hosts: localhost
  vars:
    azi: 1234567879
  tasks:

    - block:
      - name: create kp
        os_keypair:
          name: blablabla
      #       - name: "some_custom.role: segmt2: real name under role"
      #         os_networks_facts:
      #           name: "galera_net"
      #           availability_zone: "{{ azi | default(omit) }}"
      #   
      #       - debug:
      #           var: openstack_networks
      #       
      #       - set_fact:
      #           network_azs: "{{ openstack_networks[0]['availability_zones'] }}"
      #       
      #       - wait_for:
      #           port: 22
      #           host: localhost
      #         tags: "az={{azi}}"
      #           # 
      #           # - command: /usr/bin/false
      #           #   
      #           #       - debug:
      #           #           msg: "{{ item }}"
      #           #         loop: "{{network_azs}}"
      #           # 
      #       rescue:
      #         - debug:
      #             msg: "rescued"
