---
- name: test
  hosts: localhost
  vars:
    azi: 1234567879
  tasks:

    - block:
      - name: "some_custom.role: segmt2: real name under role"
        openstack.cloud.networks_facts:
          name: "admin_external_net"
        register: nets

      - debug:
          var: nets

      - wait_for:
          port: 22
          host: localhost
        tags: "az={{azi}}"
      rescue:
        - debug:
            msg: "rescued"
